server:
  port: 8080

spring:
  application:
    name: Project_ITSS
    api-prefix: /api
  datasource:
    url: jdbc:mysql://localhost:3306/aims_database?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false

# VNPay Sandbox Configuration
vnPay:
  # VNPay gateway URLs
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:5173/payment/vnpay-return
  # Merchant configuration - Updated with new sandbox credentials
  tmnCode: ZAVGV1VT
  secretKey: OR92SDL9CRPL5TOXFICMKRVASZ4FXJ4M
  # API configuration
  version: 2.1.0
  command: pay
  orderType: other
  currCode: VND
  locale: vn
  # Refund API
  apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  # Timeout configuration (in minutes)
  timeoutExpress: 15