spring:
  application:
    name: Project_ITSS
  datasource:
    url: jdbc:mysql://localhost:3306/AIMS_database?useSSL=false&serverTimezone=UTC
    username: root
    password: Kum@120304
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  vnpay:
    tmnCode: ZAVGV1VT
    hashSecret: OR92SDL9CRPL5TOXFICMKRVASZ4FXJ4M
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:8080/api/v1/payment/vn-pay-callback
    api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
